### ISSUE TITLE
Support drawing PNGs with Alpha

### ISSUE THREAD

**Issue by TheGreatRambler** [grz0zrg/fbg#10]
The image apis exposed by fbg appear to strip alpha from images. From a glance at the `_fbg_image` struct it seems that only RGB data is stored, even though alpha data is exposed by PNGs.

**Comment by grz0zrg** [comment]
This is actually two issues, first FBG use a fixed internal format which is dependent upon the rendering backend : with GLFW you can have 4 components and PNG alpha will be kept but with fbdev it is limited to 3 components so any alpha components is lost, ideally it should be independent so that any extra images information is still kept.

The second issue is rendering, how should the rendering be handled ? What is your use case ?

**Comment by TheGreatRambler** [comment]
I'm using `fbg_customSetup` with a set color depth of 4. For rendering, I would expect the image to replace the pixel data. It would be cool if it could instead layer on top of the covered pixels using the alpha data, but I don't need that now.

**Comment by TheGreatRambler** [comment]
Thank you! I'll think I might see if I can PR a composting system if I set one up.
