### ISSUE TITLE
fbg_rect didn't convert the RGB color to BGR color.

### ISSUE THREAD

**Issue by jiangming1399** [grz0zrg/fbg#6]
I am using a BGR framebuffer device, when i using fbg_rect(fbg, x, y, w, h, 255, 0, 0), it will draw a blue rect  rather than red rect on my screen.

I think maybe my screen is BGR color format, and I try to set the fbg->gbr to 1 but it didn't works.
Maybe only fbg_loadPNG and fbg_loadJPEG flip would use the fbg->gbr flag?

**Comment by grz0zrg** [comment]
Hello,

this is actually the expected behaviour, drawing primitives don't handle BGR > RGB conversion.

Only `fbg_loadPNG` and `fbg_loadJPEG` does as a convenience.

The idea behind the library is to provide a bare two-files flexible graphics library with some kickstart functions but it does not do some things like colour conversions and bounds checking to keep things bare which is probably confusing at first and i think this is not in the documentation. Maybe this should be implemented in a separate file ?

The other main idea was the parallelism which allow a compositing function to be passed to `fbg_draw` thus the conversion would be made by the main thread as a separate pass.

**Comment by jiangming1399** [comment]
Okay, I will do the BGR->RGB conversion by myself. Thank you for answering my question.
